### ISSUE TITLE
Feature: Allow selecting a guest / attraction

### ISSUE THREAD

**Issue by deurklink** [autosysops/OpenRCT2ParkMessageManager#1]
Some message types allow you to have a guest ID or attraction ID, for example guest on ride.
Would be nice if we could do that through plugin - for first version maybe allow user to type the ID himself.

**Comment by autosysops** [comment]
Making a dropdown to select a specific guest wouldn't be hard but I guess to make it really usefull you want to have a way to select the peep or ride in the park by clicking on it?

**Comment by autosysops** [comment]
Fixed in version 1.1
